# ===== Servidor =====
server.port=8080
spring.application.name=nexus-market

# ===== Base de datos MySQL =====
spring.datasource.url=jdbc:mysql://localhost:3306/nexusmarket?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://juanestevansanchezduque2_db_user:t3E84tK8y0ueYsax@ac-d6k2rvn-shard-00-00.lvupi2z.mongodb.net:27017,ac-d6k2rvn-shard-00-01.lvupi2z.mongodb.net:27017,ac-d6k2rvn-shard-00-02.lvupi2z.mongodb.net:27017/nexusmarket_audit?ssl=true&replicaSet=atlas-wyvmbe-shard-0&authSource=admin&retryWrites=true&w=majority&appName=Cluster0

# ===== Logging =====
logging.level.com.nexusmarket=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb=DEBUG